function duf=eKdV(t,uf,dummy,k)
alpha=-1/4;
beta=1;
u=ifft(uf);
u1x=ifft(1i*k.*uf);
u3xf=(1i*k).^3.*uf;
duf=-6*fft(u.*u1x)-u3xf-...
    30*alpha*beta*fft(u.^2.*u1x)-...
    20*alpha*beta*fft(u1x.*ifft((1i*k).^2.*uf))-...
    10*alpha*beta*fft(u.*ifft(u3xf))-...
    alpha*beta*fft(ifft((1i*k).^5.*uf))-...
     uf./(t+4);
end